name: MenuTestPlugin
version: 1.0.0
main: eu.okaeri.menu.test.MenuTestPlugin
api-version: 1.20
description: Test plugin for Okaeri Menu 2.0
author: Okaeri

commands:
  menu:
    description: Open test menus
    usage: /menu [type]
    aliases: [m, testmenu]
